#!/usr/bin/bash
# Maintainer  : Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=pkgmake
pkgdesc="makepkg-like tool for XBPS"
pkgver=$(date +%Y%m%d)
pkgrel=$(date +%H%M)
arch=('any')
license=('GPL3')
url="https://github.com/voidlinuxbr/$pkgname"
provides=("$pkgname")
source=("git+${url}.git")
md5sums=('SKIP')
depends=(
	"bash>=0"
	"curl>=0"
	"git>=0"
	"xbps>=0"
	"xbps-triggers>=0"
	"coreutils>=0"
	"util-linux>=0"
)

# Automatically detect and use the correct install file
if [ -e "${pkgname}.install" ]; then
	install=${pkgname}.install
elif [ -e "pkgbuild.install" ]; then
	install=pkgbuild.install
fi

package() {
	local dirs=("usr" "etc" "opt")
	#   echo "DESTDIR=$DESTDIR"
	#   echo "pkgdir=$pkgdir"
	#   echo "srcdir=$srcdir"
	#   echo "_pkgsrc=$_pkgsrc"

	cd ${srcdir}/${pkgname}
	for dir in "${dirs[@]}"; do
		if [ -d "${_pkgsrc}/${dir}" ]; then
			cp -a "${_pkgsrc}/${dir}" "$DESTDIR/"
		fi
	done
}
