#!/usr/bin/env bash
# Maintainer: Catafesta <vcatafesta@chililinux.com>

pkgname=tdb-devel
pkgver=1.4.14
_pkgver=2022.3.0
pkgrel=1
pkgdesc="Intel Threading Building Blocks"
license="Apache-2.0"
homepage="https://oneapi-src.github.io/oneTBB/"
source=("https://github.com/oneapi-src/oneTBB/archive/refs/tags/v${_pkgver}.tar.gz")

makedepends=(
	cmake
	libgomp-devel
	libhwloc-devel
	python3
	python3-devel
)

build() {
  cd "oneTBB-${_pkgver}"

  cmake -B build -S . \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DTBB_STRICT=OFF \
    -DTBB_TEST=OFF \
    -DTBB4PY_BUILD=OFF

  cmake --build build
}

package() {
   cd "oneTBB-${_pkgver}"
   DESTDIR="$DESTDIR" cmake --install build
}
