#!/usr/bin/env bash
# Maintainer: Catafesta <vcatafesta@chililinux.com>

pkgname=tdb
pkgver=1.4.14
pkgrel=1
pkgdesc="Trivial Database, similar to GDBM but allows simultaneous commits"
license="GPL-3.0-or-later"
homepage="https://tdb.samba.org/"
source=("https://download.samba.org/pub/tdb/tdb-${pkgver}.tar.gz")

makedepends=(
  pkg-config
  docbook-xsl
  libxslt
  python3-devel
)
depends=()

build() {
  cd "$pkgname-$pkgver"

  export PYTHONHASHSEED=1
  export PYTHON_CONFIG="$(command -v python3-config)"

  ./buildtools/bin/waf configure \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-rpath \
    --disable-rpath-install \
    --without-gettext \
    --builtin-libraries=replace \
    --bundled-libraries=NONE

  ./buildtools/bin/waf build
}

package() {
  cd "$pkgname-$pkgver"
  ./buildtools/bin/waf install --destdir="$PKGDIR"
}

