#!/usr/bin/env bash
# NOTE: This PKGFILE is PARTIAL and MUST be reviewed
# Maintainer: Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=samba
pkgbase=samba
pkgdesc="SMB/CIFS file, print, and login server for Unix"
pkgver=4.23.4
pkgrel=1
arch=(x86_64)
license=('GPL-3.0-or-later')
url="https://www.samba.org"
source=(https://download.samba.org/samba/ftp/stable/${pkgbase}-${pkgver}.tar.gz)
makedepends=(
	acl
	attr
	attr-devel
	autoconf
	automake
	avahi
	avahi-libs
	base-devel
	binutils
	bind
	bison
	ccache
	chrpath
	cups-devel
	curl
	dateutils
	dbus
	dbus-devel
	docbook-xml
	docbook-xsl
	flex
	gcc
	git
	glib-devel
	glusterfs
	gnutls
	gnutls-devel
	gpgme-devel
	htop
	icu-devel
	jansson
	jansson-devel
	ldns
	libarchive-devel
	libblkid-devel
	libbsd
	libbsd-devel
	libcap
	libcap-devel
	libcups
	libldap
	libldap-devel
	libnsl
	libpcap-devel
	libtasn1
	libtasn1-devel
	libtasn1-tools
	libtirpc
	libtirpc-devel
	libunwind-devel
	liburing
	libuuid-devel
	libxslt
	linux-headers
	lmdb
	lmdb-devel
	make
	mit-krb5
	mit-krb5-client
	mit-krb5-devel
	ncurses-devel
	net-tools
	pam
	pam-devel
	perl
	perl-JSON
	perl-Parse-Yapp
	perl-Text-ParseWords
	pkg-config
	popt
	popt-devel
	python
	python3
	python3-cryptography
	python3-devel
	python3-dnspython
	python3-matplotlib
	python3-pexpect
	python3-pyasn1
	readline
	readline-devel
	rpcsvc-proto
	rsync
	talloc
	tdb
	tdb-devel
	tevent
	tree
	vim
	wget
	xfsprogs-devel
	zlib-devel
	python3-devel
	perl-Parse-Yapp
	gperf
	libtirpc-devel
	linux-headers
	gnutls-devel
	jansson-devel
	lmdb-devel
	popt-devel
	readline-devel
	flex
	bison
	libxslt
	docbook-xsl
)

build() {
    cd "$srcdir/$pkgname-$pkgver"
    ./configure --prefix=/opt/samba
	make W=1 -j$(nproc)
}

package() {
    cd "$srcdir/$pkgname-$pkgver"
    make DESTDIR="$pkgdir" install
}
