#!/usr/bin/env bash
# Maintainer: Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=voidbr-fish
pkgver=4.3.2
pkgrel=1
pkgdesc='Smart and user friendly shell intended mostly for interactive use'
url='https://fishshell.com/'
arch=(x86_64)
license=('GPL-2.0-only AND BSD-3-Clause AND ISC AND MIT AND PSF-2.0')
depends=(glibc libgcc ncurses pcre2)
makedepends=(cmake git jq rust python3-Sphinx)
options=(!lto)
install=fish.install
backup=(etc/fish/config.fish)
source=("${pkgname}::git+https://github.com/fish-shell/fish-shell#tag=${pkgver}")
sha512sums=('1a165efef24a6e252b339cbc0f16a60f47d0f183b8219be89dc75df935d4b92234e036b396f7a23bc040a2a679b84973edef57346192089ddb1444676d558cf1')
b2sums=('6becf93f9483fb52047fa6c0fd9a17d72963b683a4c7602194b33f4546df692810f2246a28dade9d46db699050a8877f3c5f027c74b17847f7c59931ca9f0bd1')

build() {
	cd ${pkgname}

	export CXXFLAGS+=" ${CPPFLAGS}"

	local cmake_options=(
		-B build
		-D CMAKE_INSTALL_PREFIX=/usr
		-D CMAKE_INSTALL_SYSCONFDIR=/etc
		-D CMAKE_BUILD_TYPE=Release
		-D WITH_DOCS=ON
		-D FISH_USE_SYSTEM_PCRE2=ON
		-D WITH_GETTEXT=ON
		-W no-dev
	)
	cmake "${cmake_options[@]}"

	make -C build VERBOSE=1
}

check() {
	cd ${pkgname}
	make test
}

package() {
	cd ${pkgname}

	DESTDIR="$pkgdir" cmake --install build
}

# vim: ts=2 sw=2 et:
